# Usamos una imagen de servidor web ultra ligera basada en Linux Alpine
FROM nginx:alpine

# Copiamos un mensaje de bienvenida de prueba al servidor
RUN echo "<h1>Bienvenidos a los Canales Digitales de Promart Retail (Ecosistema DevOps)</h1>" > /usr/share/nginx/html/index.html

# Exponemos el puerto 80 del contenedor
EXPOSE 80
